name: 스프링 배치 테스트 자동화

on:
  push:
    branches:
      - main
      - develop
      - develop-feat/**
    paths: 'batch/**'
  pull_request:
    branches:
      - main
      - develop
      - develop-feat/**
    paths: 'batch/**'

defaults:
  run:
    working-directory: batch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: JDK 11을 설치합니다.
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: git secret 저장된 값을 가져옵니다.
        env:
          OCCUPY_SECRET: ${{ secrets.OCCUPY_SECRET }}
          OCCUPY_SECRET_DIR: batch/src/main/resources
          OCCUPY_SECRET_DIR_FILE_NAME: application.yml
        run: echo $OCCUPY_SECRET | base64 --decode > $OCCUPY_SECRET_DIR/$OCCUPY_SECRET_DIR_FILE_NAME  
      

      - name: TimeZone을 Asia/Seoul로 설정합니다
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Seoul

      - name: Gradle 명령 실행을 위한 권한을 부여합니다
        run: chmod +x gradlew

      - name: Gradle build를 수행합니다
        run: ./gradlew build

      - name: 테스트 결과를 PR에 코멘트로 등록합니다
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'

